/********************************************
 * File: events.h
 * Description: This file defines any external events related
 * 		to the MiniMixer board.
 *
 * 		This includes encoder and CapTouch events, as well as anything
 * 		not generated by the bluetooth module
 */


#ifndef EVENTS_H
#define EVENTS_H


// Board Hardware Generated Events
typedef enum{
	CAP_MEASURE_START = 0x00000001,
	CAP_MEASURE_READY = 0x00000002,
	CAP_MEASURE_END = 0x0000004,
	ENC_1 = 0x00000004,
	ENC_2 = 0x00000008,
	ENC_3 = 0x00000010
} event_t;


#endif	//EVENTS_H
